// Build-time machine translation of UI strings (en.ts) into low-resource locales with the same NLLB
// model the app uses at run time. Placeholders like {n} are protected; a string whose placeholders do
// not survive falls back to English and is listed in the report. Output is MACHINE TRANSLATION,
// unreviewed by native speakers, and is labelled as such in the app.
// Usage: npx tsx scripts/translate-ui.ts rw sw
import { pipeline } from '@huggingface/transformers';
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { en } from '../src/i18n/en';
import { TRANSLATION_MODEL } from '../src/model/config';

async function main() {
const locales = process.argv.slice(2);
const translator = await pipeline('translation', TRANSLATION_MODEL.id, { dtype: 'q8' });

const protect = (s: string) => { const ph: string[] = []; const text = s.replace(/\{\w+\}/g, m => { ph.push(m); return `[${ph.length}]`; }); return { text, ph }; };
const restore = (s: string, ph: string[]) => ph.reduce((acc, p, i) => acc.replace(new RegExp(`\\[\\s*${i + 1}\\s*\\]`), p), s);

for (const locale of locales) {
  const tgt = TRANSLATION_MODEL.languages[locale];
  if (!tgt) throw new Error(`no model language for ${locale}`);
  const out: Record<string, string> = {}; const fallback: string[] = [];
  const t0 = Date.now();
  for (const [key, value] of Object.entries(en)) {
    // Brand/glyph-only and very short technical strings stay as-is.
    if (key === 'app.name' || !/[A-Za-z]{2}/.test(value)) { out[key] = value; continue; }
    const { text, ph } = protect(value);
    const lines = text.split('\n');
    const translated: string[] = [];
    for (const line of lines) translated.push(line.trim() ? (await translator(line, { src_lang: TRANSLATION_MODEL.sourceLanguage, tgt_lang: tgt, max_new_tokens: 200 }) as any)[0].translation_text : line);
    const result = restore(translated.join('\n'), ph);
    const ok = ph.every(p => result.includes(p)) && !/\[\d+\]/.test(result);
    out[key] = ok ? result : value;
    if (!ok) fallback.push(key);
  }
  const file = path.resolve(__dirname, `../src/i18n/${locale}.ts`);
  writeFileSync(file, `// MACHINE TRANSLATION (${TRANSLATION_MODEL.id}, ${TRANSLATION_MODEL.license}) of en.ts — not reviewed by a native speaker.
// Generated by scripts/translate-ui.ts on ${new Date().toISOString()}. Keys falling back to English: ${fallback.length}.
import type { Messages } from './en';

export const ${locale}: Partial<Messages> = ${JSON.stringify(out, null, 2)};
export const ${locale}Fallback = ${JSON.stringify(fallback)};
`);
  console.log(`${locale}: ${Object.keys(out).length} strings, ${fallback.length} English fallbacks, ${((Date.now() - t0) / 1000).toFixed(0)} s`);
}
}
main().catch(e => { console.error(e); process.exitCode = 1; });
